/* PickStar: classic script supports Chrome file:// without a server. */
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const areas=['图书馆','教学区','生活区','运动场','北门'];
const categories=['电子产品','证件卡包','钥匙','书籍文具','衣物配饰','其他'];
const labels={seeking:'寻找中',claimed:'待认领',found:'已找回',returned:'已归还'};
const coords={'图书馆':[68,39],'教学区':[60,27],'生活区':[28,56],'运动场':[50,80],'北门':[72,12]};
const pages={home:'01 天枢·星图首页',map:'02 校园星图',search:'03 天璇·寻觅星点',detail:'04 天玑·观星识物',publish:'05 天权·登记星启',success:'06 星启发布成功',profile:'07 我的星册',bind:'08 绑定手机',verify:'09 校园实名认证',progress:'10 认证进度与结果',return:'11 开阳·星物归还',thanks:'12 摇光·赠玫瑰致谢'};
const roseColors={red:['红色','#db526a'],blue:['蓝色','#548fe1'],yellow:['黄色','#e7bc3f'],pink:['粉色','#ed91b7'],orange:['橙色','#ef9448'],purple:['紫色','#a178cf']};
function makeRose(message,from){const colors=Object.keys(roseColors);return {message,from,color:colors[Math.floor(Math.random()*colors.length)],receivedAt:new Date().toISOString()}}
function roseDate(rose){if(!rose.receivedAt)return '日期未记录';const d=new Date(rose.receivedAt);return Number.isNaN(d.getTime())?'日期未记录':d.toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'})}
function rosePot(color){const [name,fill]=roseColors[color]||roseColors.red;return `<svg class="rose-pot" viewBox="0 0 150 180" role="img" aria-label="${name}玫瑰盆栽"><ellipse cx="75" cy="168" rx="43" ry="6" fill="#ddd5e8" opacity=".45"/><path d="M75 126V60" stroke="#6b9c83" stroke-width="5" fill="none"/><path d="M74 108Q37 109 43 85Q69 84 74 108M77 93Q111 94 109 71Q83 72 77 93" fill="#91b49a"/><g fill="${fill}" stroke="#fff" stroke-opacity=".45" stroke-width="1.5"><path d="M75 70C38 72 27 48 43 34C41 14 68 10 78 24C99 10 122 31 109 48C113 65 90 77 75 70Z"/><path d="M50 39Q72 22 97 37Q105 56 76 63Q52 61 50 39Z"/><path d="M63 35Q84 29 92 45Q87 59 71 52Q58 46 71 40Q82 37 83 46" fill="none" stroke="#fff" stroke-opacity=".7" stroke-width="2.5"/></g><path d="M45 126H105L97 158Q75 173 53 158Z" fill="#c6b4d6"/><path d="M44 125H106" stroke="#e6d9ef" stroke-width="12" stroke-linecap="round"/><path d="m75 137 3 7 8 1-6 5 1 8-6-4-7 4 2-8-6-5 8-1Z" fill="#fff2bf"/></svg>`}
function roseGarden(roses){return roses.length?`<div class="rose-garden">${roses.map(i=>`<article class="rose-tile">${rosePot(i.rose.color)}<h3>${(roseColors[i.rose.color]||roseColors.red)[0]}玫瑰</h3><time datetime="${esc(i.rose.receivedAt||'')}">赠送日期：${esc(roseDate(i.rose))}</time><p>来自 ${esc(i.rose.from||'热心同学')}</p><p class="rose-message">${esc(i.rose.message||'谢谢你，让星星回家。')}</p><small>关于 · ${esc(i.title)}</small></article>`).join('')}</div>`:'<div class="notice">小花园正在等待第一份感谢。收到玫瑰后，这里会记录颜色、祝福和赠送日期。</div>'}
const slogans=[['Pick the lost stars, send roses in return.','拾起散落星辰，归还赠以玫瑰。'],['PickStar · Retrieve your lost star.','PickStar · 寻回属于你的星辰。'],['Pick a star, reunite belongings.','拾取星光，物归原主。']];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const seed=[
 {id:'s1',title:'黑色蓝牙耳机',category:'电子产品',area:'图书馆',date:'2026-10-03',type:'lost',status:'seeking',description:'图书馆二层靠窗座位附近遗失，耳机盒上有一颗小星星贴纸。',contact:'13800000001',owner:true,publisher:'Nova',finder:'小面包',icon:'🎧'},
 {id:'s2',title:'星星卡套里的校园卡',category:'证件卡包',area:'教学区',date:'2026-10-04',type:'found',status:'claimed',description:'在教学楼走廊拾到。请联系时核对卡片姓名和卡套特征。',contact:'13800000002',owner:false,publisher:'小面包',finder:'小面包',icon:'✉'},
 {id:'s3',title:'蓝色保温杯',category:'其他',area:'运动场',date:'2026-10-02',type:'found',status:'returned',description:'已与失主核对并完成线下交接，谢谢每一份善意。',contact:'13800000002',owner:false,publisher:'小面包',finder:'小面包',recipient:'me',icon:'☕'},
 {id:'s4',title:'月亮挂件钥匙串',category:'钥匙',area:'生活区',date:'2026-10-01',type:'lost',status:'found',description:'钥匙已找回，准备向拾主送出一份感谢。',contact:'13800000001',owner:true,publisher:'Nova',finder:'小面包',recipient:'me',icon:'🗝'},
 {id:'s5',title:'一本手写课堂笔记',category:'书籍文具',area:'北门',date:'2026-10-04',type:'found',status:'claimed',description:'米色封面，里面有蓝色墨水笔记。',contact:'13800000001',owner:true,publisher:'Nova',finder:'Nova',icon:'📖'}
];
function read(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return value??fallback}catch{return fallback}}
let items=read('pickstar-v2-items',seed), user=read('pickstar-v2-user',{bound:false,phone:'',verification:'none'});
if(!Array.isArray(items))items=seed;if(!user||typeof user!=='object')user={bound:false,phone:'',verification:'none'};
const accountNames=['Nova','小面包','星星同学'];
let activeAccount=read('pickstar-active-account','Nova');
if(!accountNames.includes(activeAccount))activeAccount='Nova';
const storedAccounts=read('pickstar-accounts',{});
const accounts=Object.fromEntries(accountNames.map(name=>[name,storedAccounts?.[name]|| (name==='Nova'?user:{bound:false,phone:'',verification:'none'})]));
user=accounts[activeAccount];
const accountDrafts={};
function isOwner(item){return item.publisher===activeAccount}
function recipientOf(item){return item.recipient==='me'?'Nova':item.recipient}
function switchAccount(name){
 if(!accountNames.includes(name))return;
 captureDraft();accountDrafts[activeAccount]=draft;accounts[activeAccount]=user;
 activeAccount=name;user=accounts[name];draft=accountDrafts[name]||{};codeSent=false;backTo='profile';mapMode='browse';
 if(save()){$('#modal').close();route='profile';render()}
}
const samplePhotos={s1:'assets/earbuds.jpg',s2:'assets/card-holder.jpg',s3:'assets/bottle.jpg',s5:'assets/notebook.jpg'};
// Add supplied photos to existing demo records without resetting saved status or user uploads.
items.forEach(x=>{if(samplePhotos[x.id]&&!x.photo)x.photo=samplePhotos[x.id]});
let route='home',selected='s1',mapMode='browse',backTo='profile',draft={},filter={keyword:'',category:'',area:'',date:'',status:''},codeSent=false;
function save(){try{localStorage.setItem('pickstar-v2-items',JSON.stringify(items));accounts[activeAccount]=user;localStorage.setItem('pickstar-accounts',JSON.stringify(accounts));localStorage.setItem('pickstar-active-account',JSON.stringify(activeAccount));return true}catch{modal('保存失败','浏览器存储空间不足或被禁用。请减少图片大小后重试。');return false}}
function modal(title,body){$('#modal-body').innerHTML=`<h2>${title}</h2>${body}`;if(!$('#modal').open)$('#modal').showModal()}
const star=(status,extra='')=>`<span class="star ${status} ${extra}" aria-label="${labels[status]}">✦</span>`;
const button=(text,go,cls='')=>`<button class="${cls}" data-go="${go}">${text}</button>`;
const dipper=`<svg class="dipper" viewBox="0 0 330 185" aria-hidden="true"><path d="M20 140 L80 110 L140 120 L188 84 L240 100 L290 45 L235 20 L188 84" fill="none" stroke="#9b91c9" stroke-width="1.5" stroke-dasharray="4 5"/>${[[20,140],[80,110],[140,120],[188,84],[240,100],[290,45],[235,20]].map(([x,y])=>`<circle cx="${x}" cy="${y}" r="4" fill="#b4a2dc"/><text x="${x-8}" y="${y+7}" fill="#a99cd1" font-size="25">✧</text>`).join('')}</svg>`;
function hero(title,index=0){return `<section class="hero">${dipper}<div class="eyebrow">PICKSTAR / FOLLOW THE BIG DIPPER</div><h1>${title}</h1><p class="english">${slogans[index][0]}</p><p class="art">${slogans[index][1]}</p></section>`}
function options(list,value,first='全部'){return `<option value="">${first}</option>`+list.map(x=>`<option ${value===x?'selected':''}>${esc(x)}</option>`).join('')}
function notes(list){return list.length?`<div class="cards">${list.map(x=>`<button class="note ${['found','returned'].includes(x.status)?'settled':'active-note'}" data-item="${esc(x.id)}">${star(x.status)}<span class="badge">${labels[x.status]}</span><h3>${esc(x.title)}</h3>${x.photo?`<span class="note-window"><img src="${esc(x.photo)}" alt="${esc(x.title)}实物照片" loading="lazy"></span>`:`<p class="note-description">${esc(x.description.slice(0,100))}</p>`}<p class="muted">⌖ ${esc(x.area)} · ${esc(x.date)}</p><small>${x.type==='lost'?'寻物启事':'拾物招领'}　${esc(x.publisher)}</small></button>`).join('')}</div>`:'<p class="empty">✧ 暂时没有找到星星，试着调整筛选条件。</p>'}
function mapView(){return `<div class="map" id="campus-map"><img src="assets/campus-night.png" alt="福州大学校园夜景手绘地图">${items.map(x=>{const p=x.point||coords[x.area]||[50,50];return `<button class="pin" style="left:${p[0]}%;top:${p[1]}%" data-pin="${esc(x.id)}" aria-label="${esc(x.title)} ${labels[x.status]}">${star(x.status)}</button>`}).join('')}</div><div class="map-caption">${Object.entries(labels).map(([k,v])=>`${star(k)} ${v}`).join('　')}</div>`}
function current(){return items.find(x=>x.id===selected)||items[0]}
function filtered(){return items.filter(x=>(!filter.keyword||`${x.title} ${x.description}`.toLowerCase().includes(filter.keyword.toLowerCase().trim()))&&(!filter.category||x.category===filter.category)&&(!filter.area||x.area===filter.area)&&(!filter.date||x.date>=filter.date)&&(!filter.status||x.status===filter.status))}
function fields(){return `<div class="filters"><label>品类<select name="category">${options(categories,filter.category)}</select></label><label>地点<select name="area">${options(areas,filter.area)}</select></label><label>此日期之后<input type="date" name="date" value="${esc(filter.date)}"></label><label>状态<select name="status"><option value="">全部</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${filter.status===k?'selected':''}>${v}</option>`).join('')}</select></label></div>`}
function render(){const x=current();let html='';
 $('#account-menu').innerHTML=`<button data-action="accounts">◉ ${esc(activeAccount)} · 切换账号</button>`;
 if(route==='home')html=hero('天枢 · 星图首页')+`<form class="searchbar" data-form="search"><input name="keyword" aria-label="搜索物品" placeholder="寻一颗星，找一件心爱之物……"><button class="primary">寻觅星点</button><button type="button" data-action="filters">筛选 ☷</button></form><div class="layout"><section class="panel"><div class="section-title"><h2>校园星图</h2>${button('展开地图 ↗','map')}</div>${mapView()}</section><aside class="panel"><p class="eyebrow">A LITTLE LIGHT, A LITTLE KINDNESS</p><h2>每一颗星<br>都在等一个归途。</h2><p class="english">Lost, found,<br>and loved again.</p><p>让寻找有迹可循，让善意被温柔收藏。</p><div class="actions">${button('✦ 我丢失了','publish','primary')}<button class="purple" data-action="found-publish">✦ 我捡到了</button></div></aside></div><div class="section-title"><h2>散落在校园的星星</h2>${button('寻觅全部 →','search')}</div>${notes(items)}`;
 if(route==='map')html=hero('校园星图 · 循光而行',2)+`<section class="panel"><p>${mapMode==='select'?'点击地图任意位置选择发布地点；星点位置仅为示意。':'点击发光星点，查看物品线索。'}</p>${mapView()}<div class="actions"><button data-action="locate">◎ 立即定位（演示）</button><button data-action="manual">⌖ 手动选点</button>${button('返回发布','publish')}</div></section>`;
 if(route==='search')html=hero('天璇 · 寻觅星点',1)+`<form data-form="search" class="panel"><div class="searchbar"><input name="keyword" value="${esc(filter.keyword)}" placeholder="物品名称或特征" aria-label="关键词"><button class="primary">寻找</button><button type="button" data-action="clear-filter">重置</button></div>${fields()}</form><p class="muted">找到 ${filtered().length} 颗星星</p>${notes(filtered())}`;
 if(route==='detail')html=hero('天玑 · 观星识物',1)+`<div class="layout"><section class="panel"><h2>${esc(x.title)}</h2>${star(x.status)} <span class="badge">${labels[x.status]}</span><p>${esc(x.description)}</p><div class="facts"><div><small>登记地点</small>${esc(x.area)}</div><div><small>日期</small>${esc(x.date)}</div><div><small>发布者</small>${esc(x.publisher)}</div><div><small>类别</small>${esc(x.category)}</div></div></section><aside class="panel" id="contact-panel" tabindex="-1"><h2>玉衡 · 星语核验</h2><p>联系前，请核对物品的颜色、外观与遗失时间。交接时请在校园公共场所见面。</p><div class="notice">${user.verification==='approved'?`联系方式：<b>${esc(x.contact)}</b><div class="actions"><button data-action="copy">复制联系方式</button></div>`:'通过校园认证后，可查看完整联系方式。'} </div>${user.verification==='approved'?'':`<button class="primary" data-action="contact-auth">认证后查看</button>`}<div class="actions">${isOwner(x)&&['seeking','claimed'].includes(x.status)?button('确认找回 / 归还','return','primary'):''}${canThank(x)?button('🌹 赠人玫瑰','thanks'):''}</div><p class="english">Every star has a story.</p></aside></div>`;
 if(route==='publish')html=hero('天权 · 登记星启',2)+`<form data-form="publish" class="panel form" novalidate><div class="two"><label class="notice"><input type="radio" name="type" value="lost" ${draft.type!=='found'?'checked':''}> ${star('seeking')} 我丢失了</label><label class="notice"><input type="radio" name="type" value="found" ${draft.type==='found'?'checked':''}> ${star('claimed')} 我捡到了</label></div><label>物品名称<input name="title" maxlength="60" value="${esc(draft.title)}" placeholder="给这颗星星一个名字"></label><div class="two"><label>物品类别<select name="category">${options(categories,draft.category,'请选择')}</select></label><label>遗失 / 拾取日期<input type="date" name="date" max="${today()}" value="${esc(draft.date||today())}"></label></div><label>登记地点<select name="area">${options(areas,draft.area,'请选择')}</select></label><button type="button" data-action="choose-place">⌖ 到校园星图选点</button><label>物品照片（可选，最大 2MB）<input type="file" name="photo" accept="image/png,image/jpeg,image/webp"></label>${draft.photo?'<p class="muted">照片已保留</p>':''}<label>特征描述<textarea name="description" maxlength="500">${esc(draft.description)}</textarea></label><label>联系手机<input name="contact" inputmode="tel" value="${esc(draft.contact||user.phone)}" maxlength="11"></label><p class="muted">${user.bound?'手机已绑定':'发布前需要绑定手机，已填写内容将保留。'}</p><button class="primary">✧ 点亮这颗星</button></form>`;
 if(route==='success')html=hero('星启发布成功',0)+`<section class="panel center">${star(x.status,'giant')}<h2>你的星星，已经点亮。</h2><p>「${esc(x.title)}」正在等待回应。</p><div class="actions">${button('查看详情','detail','primary')}${button('返回首页','home')}</div></section>`;
 if(route==='profile'){const mine=items.filter(i=>isOwner(i)),roses=items.filter(i=>i.rose&&i.finder===activeAccount);html=hero('我的星册 · 收藏善意',0)+`<section class="panel profile-identity"><img class="profile-avatar" src="assets/avatar-nova.svg" alt="${esc(activeAccount)} 的星夜头像"><div><h2>✧ ${esc(activeAccount)} 的星册</h2><p>手机 ${user.bound?esc(user.phone):'未绑定'} · 认证 ${verificationName()}</p><div class="actions">${button('手机绑定','bind')}${button('校园实名认证','verify')}${button('查看认证进度','progress')}</div></div></section><div class="stats"><div><b>${mine.length}</b>我的发布</div><div><b>${roses.length}</b>收到的玫瑰</div><div><b>${mine.filter(i=>['found','returned'].includes(i.status)).length}</b>星物归途</div></div><h2>我的发布</h2>${notes(mine)}<div class="section-title"><h2>我的玫瑰小花园</h2><small>每一盆，都是一份被珍藏的感谢</small></div>${roseGarden(roses)}`;}
 if(route==='bind')html=hero('绑定手机 · 留下星语',1)+`<form data-form="bind" class="panel form"><h2>${user.bound?'手机已绑定 ✓':'建立一份温柔的联系'}</h2><label>手机号码<input name="phone" inputmode="tel" maxlength="11" value="${esc(user.phone)}" required></label><label>验证码<input name="code" maxlength="6" placeholder="演示验证码 123456" required></label><div class="notice">仅模拟绑定，不会发送短信。点击获取验证码后输入 123456。</div><div class="actions"><button type="button" data-action="sms">获取演示验证码</button><button class="primary">确认绑定</button></div></form>`;
 if(route==='verify')html=hero('校园实名认证 · 点亮信任',1)+`<form data-form="verify" class="panel form"><div class="notice">课程模拟认证，请填写虚构资料。提交不代表审核通过；演示证件只在当前页面检查，不保存到本地。</div><label>姓名<input name="name" maxlength="30" required></label><label>学号<input name="student" pattern="[0-9]{9}" maxlength="9" required></label><label>绑定电话<input readonly value="${esc(user.phone||'请先绑定手机')}"></label><label>学生证图片（演示素材，最大 2MB）<input type="file" name="studentPhoto" accept="image/png,image/jpeg,image/webp" required></label><div class="actions">${button('绑定手机','bind')}<button class="primary">提交认证</button></div></form>`;
 if(route==='progress')html=hero('认证进度与结果',1)+`<section class="panel form"><div class="progress"><span class="current">提交资料</span><span class="${user.verification==='pending'?'current':''}">等待审核</span><span class="${['approved','rejected'].includes(user.verification)?'current':''}">审核结果</span></div><h2>${verificationName()}</h2><p>${({none:'尚未提交校园认证。',pending:'资料已提交，正在等待审核。提交不代表通过。',approved:'认证已通过，可以查看并复制联系方式。',rejected:'演示审核未通过：证件信息不清晰，请重新提交。'})[user.verification]}</p><div class="actions">${button(user.verification==='rejected'?'重新提交':'前往认证','verify')}${button('返回星册','profile')}${user.verification==='approved'?button('返回物品详情','detail','primary'):''}</div><details><summary>演示审核状态切换</summary><p class="muted">仅用于课程演示，没有真实审核服务。</p><div class="actions"><button data-review="pending">待审核</button><button data-review="approved">通过</button><button data-review="rejected">未通过</button></div></details></section>`;
 if(route==='return')html=hero('开阳 · 星物归还',2)+`<section class="panel center">${star(x.status,'giant')}<h2>${esc(x.title)}</h2><p>当前状态：${labels[x.status]}</p><p>请在线下核验并完成交接后，再确认状态。</p>${isOwner(x)&&['seeking','claimed'].includes(x.status)?`<button class="primary" data-action="finish">确认${x.type==='lost'?'已找回':'已归还'}</button>`:`<p class="notice">${isOwner(x)?'这颗星星已完成交接。':'只有发布者可以更新这条信息。'}</p>`}<div class="actions">${button('查看详情','detail')}${canThank(x)?button('🌹 赠人玫瑰','thanks','purple'):''}</div></section>`;
 if(route==='thanks')html=hero('摇光 · 赠玫瑰致谢',0)+`<form data-form="thanks" class="panel form center"><div class="rose">🌹</div><h2>把星光，折成一朵玫瑰。</h2><p>物品：${esc(x.title)} · 拾主：${esc(x.finder||x.publisher)}</p><label>你的感谢语<textarea name="message" maxlength="200" placeholder="谢谢你替我守护这颗星……"></textarea></label><p class="muted">每次交接最多一朵，自愿赠送，也可以跳过。</p>${canThank(x)?'<button class="purple">赠送玫瑰</button>':`<p class="notice">${x.rose?'这次交接已经送过玫瑰。':'完成交接后，由失主赠送感谢。'}</p>`} ${button('跳过，返回星册','profile')}</form>`;
 $('#app').innerHTML=html;document.title=`${pages[route]} · 拾星`;}
function verificationName(){return ({none:'未认证',pending:'待审核',approved:'已通过',rejected:'未通过'})[user.verification]||'未认证'}
function canThank(x){return ['found','returned'].includes(x.status)&&!x.rose&&x.finder!==activeAccount&&accountNames.includes(x.finder)&&(recipientOf(x)===activeAccount||(isOwner(x)&&x.type==='lost'))}
function go(page){if(!pages[page])page='home';if(page!=='success')captureDraft();route=page;render();window.scrollTo(0,0)}
function captureDraft(){const form=$('[data-form="publish"]');if(form){const data=Object.fromEntries(new FormData(form));delete data.photo;draft={...draft,...data};}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.account){switchAccount(b.dataset.account);return}
 if(b.dataset.go){$('#modal').close();go(b.dataset.go);return}if(b.dataset.item){selected=b.dataset.item;go('detail');return}
 if(b.dataset.pin){const x=items.find(i=>i.id===b.dataset.pin);modal(`${star(x.status)} ${esc(x.title)}`,`<p>${esc(x.area)} · ${labels[x.status]}</p><p>${esc(x.description)}</p><button data-preview="${esc(x.id)}">查看详情</button>`);return}
 if(b.dataset.preview){selected=b.dataset.preview;$('#modal').close();go('detail');return}
 if(b.dataset.review){user.verification=b.dataset.review;if(save())render();return}
 const a=b.dataset.action;if(a==='accounts'){modal('模拟登录 · 选择账号',`<p>三个账号共享物品信息，分别保存手机绑定、认证和个人星册。</p><div class="actions">${accountNames.map(name=>`<button data-account="${name}" class="${name===activeAccount?'primary':''}">${name}${name===activeAccount?' · 当前':''}</button>`).join('')}</div><p class="muted">本地演示，无需密码，不连接真实账号服务。</p>`);return}if(a==='filters')modal('筛选星点',`<form data-form="filter">${fields()}<button class="primary">应用筛选</button></form>`);
 if(a==='clear-filter'){filter={keyword:'',category:'',area:'',date:'',status:''};render()}
 if(a==='found-publish'){draft.type='found';go('publish')}
 if(a==='choose-place'){captureDraft();mapMode='select';go('map')}
 if(a==='manual'){mapMode='select';render()}
 if(a==='locate')modal('定位失败 · 星光仍可抵达','<p>当前为模拟地图，未请求真实定位。请手动在校园地图中选择位置。</p><button data-action="resume-map">手动选点</button>');
 if(a==='resume-map'){mapMode='select';$('#modal').close();render()}
 if(a==='sms'){codeSent=true;modal('演示验证码','<p>验证码为 <b>123456</b>，未发送真实短信。</p>')}
 if(a==='contact-auth'){backTo='verify';go(user.bound?'verify':'bind')}
 if(a==='copy'&&user.verification==='approved'){try{await navigator.clipboard.writeText(current().contact);modal('复制成功','<p>联系方式已复制。请先核对物品特征。</p>')}catch{modal('请手动复制',`<p>当前浏览器未允许自动复制，可选中下方号码复制。</p><input readonly value="${esc(current().contact)}">`)}}
 if(a==='finish'){const x=current();if(!isOwner(x)||!['seeking','claimed'].includes(x.status))return;modal('确认完成交接',`<p>确认「${esc(x.title)}」已${x.type==='lost'?'找回':'归还'}？此操作将结束当前寻找。</p><label>${x.type==='lost'?'拾主账号（玫瑰接收人）':'失主账号（可赠送玫瑰）'}<select id="handover-account">${accountNames.filter(n=>n!==activeAccount).map(n=>`<option value="${n}" ${n===(x.type==='lost'?x.finder:recipientOf(x))?'selected':''}>${n}</option>`).join('')}</select></label><button class="primary" data-action="confirm-finish">确认更新状态</button>`)}
 if(a==='confirm-finish'){const x=current();if(!isOwner(x)||!['seeking','claimed'].includes(x.status))return;const partner=$('#handover-account').value;if(!accountNames.includes(partner)||partner===activeAccount){modal('请选择交接对象','<p>请先确认与哪位同学完成了交接。</p>');return}if(x.type==='lost'){x.finder=partner;x.recipient=activeAccount}else{x.finder=activeAccount;x.recipient=partner}x.status=x.type==='lost'?'found':'returned';if(save()){$('#modal').close();render()}}
});
document.addEventListener('click',e=>{const map=e.target.closest('#campus-map');if(!map||mapMode!=='select'||route!=='map'||e.target.closest('button'))return;const rect=map.getBoundingClientRect();draft.point=[+(100*(e.clientX-rect.left)/rect.width).toFixed(2),+(100*(e.clientY-rect.top)/rect.height).toFixed(2)];modal('选定一颗星的位置',`<form data-form="place"><p>已记录地图选点。请选择该位置所属区域：</p><select name="area">${options(areas,draft.area,'请选择区域')}</select><button class="primary">确认选址，返回发布</button></form>`)});
document.addEventListener('change',e=>{if(e.target.name==='photo'){const f=e.target.files[0];if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>2*1024*1024){e.target.value='';modal('图片不符合要求','<p>请选择不超过 2MB 的 PNG、JPG 或 WebP 图片。</p>');return}const uploadAccount=activeAccount;const reader=new FileReader();reader.onload=()=>{if(activeAccount===uploadAccount)draft.photo=reader.result};reader.readAsDataURL(f)}});
document.addEventListener('submit',e=>{const form=e.target,kind=form.dataset.form;if(!kind)return;e.preventDefault();const d=Object.fromEntries(new FormData(form));
 if(kind==='search'||kind==='filter'){filter={...filter,...d};$('#modal').close();go('search')}
 if(kind==='place'){if(!areas.includes(d.area))return;draft.area=d.area;mapMode='browse';$('#modal').close();go('publish')}
 if(kind==='publish'){captureDraft();const errors=[];if((d.title||'').trim().length<2)errors.push('物品名称至少填写两个字。');if(!categories.includes(d.category))errors.push('请选择物品类别。');if(!areas.includes(d.area))errors.push('请选择登记地点。');if(!d.date||d.date>today())errors.push('请选择今天或之前的日期。');if(!/^1\d{10}$/.test(d.contact))errors.push('请填写 11 位手机号码。');if(!(d.description||'').trim())errors.push('请填写物品特征描述。');if(errors.length){modal('表单需要补充',`<ul class="error">${errors.map(v=>`<li>${v}</li>`).join('')}</ul>`);return}if(!user.bound){backTo='publish';go('bind');return}const x={...draft,id:`star-${Date.now()}`,title:d.title.trim(),description:d.description.trim(),status:d.type==='lost'?'seeking':'claimed',owner:true,publisher:activeAccount,finder:d.type==='found'?activeAccount:'',icon:'✧'};items.unshift(x);if(!save()){items.shift();return}selected=x.id;draft={};go('success')}
 if(kind==='bind'){if(!/^1\d{10}$/.test(d.phone)||!codeSent||d.code!=='123456'){modal('绑定失败','<p>请填写 11 位手机号码，获取演示验证码并输入 123456。</p>');return}user.bound=true;user.phone=d.phone;if(save()){go(backTo);modal('手机绑定成功','<p>已返回原页面，填写中的发布信息已保留。</p>')}}
 if(kind==='verify'){if(!user.bound){backTo='verify';go('bind');return}const file=form.elements.studentPhoto.files[0];if(!d.name.trim()||!/^\d{9}$/.test(d.student)||!file||!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>2*1024*1024){modal('认证资料需要补充','<p>请填写姓名、9 位学号，上传不超过 2MB 的演示证件图片。</p>');return}user.verification='pending';if(save())go('progress')}
 if(kind==='thanks'){const x=current();if(!canThank(x))return;x.rose=makeRose(d.message.trim(),activeAccount);if(save()){go('profile');modal('玫瑰祝福 · 已送达',`<div class="center">${rosePot(x.rose.color)}<p>${roseColors[x.rose.color][0]}玫瑰 · ${esc(roseDate(x.rose))}</p><h3>致 ${esc(x.finder||x.publisher)}</h3><p>${esc(d.message.trim()||'谢谢你，让遗失的星星回家。')}</p></div>`)}}
});
const navigationStars=[
 ['home','天枢','星图首页',86,25],['search','天璇','寻觅星点',78,66],
 ['detail','天玑','观星识物',57,61],['publish','天权','登记星启',53,20],
 ['profile','玉衡','我的星册',36,32],['return','开阳','星物归还',22,55],
 ['thanks','摇光','赠玫瑰致谢',8,43]
];
// 连线和按钮共用同一组坐标，星点的中心即连线顶点。
const navigationPath=[0,1,2,3,0,3,4,5,6].map((index,i)=>`${i?'L':'M'}${navigationStars[index][3]} ${navigationStars[index][4]}`).join(' ');
$('#page-links').innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path d="${navigationPath}"/></svg>`+navigationStars.map(([page,name,label,left,top])=>`<button class="nav-star" data-go="${page}" style="left:${left}%;top:${top}%" aria-label="${name}·${label}"><span class="nav-star-icon" aria-hidden="true">✦</span><span class="nav-star-label">${name} · ${label}</span></button>`).join('');
window.addEventListener('hashchange',()=>go(location.hash.slice(1)));go(pages[location.hash.slice(1)]?location.hash.slice(1):'home');
